dist: bionic
jobs:
  include:
    - language: python
      python: 3.6
      install: 
        - pip install -U pip setuptools wheel
        - pip install -r requirements.txt
      script: 
        - make lint
    - language: python
      python: 3.7
      install: 
        - pip install -U pip setuptools wheel
        - pip install -r requirements.txt
      script: 
        - make lint
    - language: python
      python: 3.8
      install: 
        - pip install -U pip setuptools wheel
        - pip install -r requirements.txt
      script: 
        - make lint
   # Julia jobs  
    - language: julia
      julia: 1.0.5
      script:
        - julia --project=julia/src -e 'using Pkg; Pkg.instantiate(); Pkg.build();'
    - language: julia
      julia: 1.4.2
      script:
        - julia --project=julia/src -e 'using Pkg; Pkg.instantiate(); Pkg.build();'   
