python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
jobs:
  include:
    - stage "Requirements"
      language: python
      script: make requirements
    - stage "Lint"
      language: python
      script: make lint
